### ISSUE TITLE
Regarding execution of the project

### ISSUE THREAD

**Issue by vasanthkumaur** [nitinsinghnaruka/timesheet#1]
Hi, can you please explain to me how to run this project?

**Comment by nitinsinghnaruka** [comment]
Yes sure.

For the setup, you have to install Node JS, Composer (PHP), and Xampp.

Place the project in the xampp/htdocs/

Open command prompt and go to your project installation directory in this.

Write - cd timesheet

> timesheet > composer install
> timesheet > npm install
> timesheet > npm run production

And hit this "localhost/timesheet/public" in browser.

Your project will now work.

You can also change the url by creating virtual host, I can explain it for
you if you want.

Feel free to contact me if you have any questions or concerns.

Thank you,

Regards
Nitin Singh Naruka

**Comment by nitinsinghnaruka** [comment]
Yes sure.

For the setup, you have to install Node JS, Composer (PHP), and Xampp.

Place the project in the xampp/htdocs/

Open command prompt and go to your project installation directory in this.

Write -

`
$ cd timesheet
$ timesheet > composer install
$ timesheet > npm install
$ timesheet > npm run production
`
And hit this "localhost/timesheet/public" in browser.

Your project will now work.

You can also change the url by creating virtual host, I can explain it for
you if you want.

**Comment by vasanthkumaur** [comment]
500
Whoops, something went wrong on our servers.

I am getting this error while running(http://localhost/timesheet/public/) in the web browser.

**Comment by nitinsinghnaruka** [comment]
> 500
> Whoops, something went wrong on our servers.
> 
> I am getting this error while running(http://localhost/timesheet/public/) in the web browser.

I forgot something to explain.

- Make sure to copy .env-example to .env

- Run command to generate key

`$ php artisan key generate` from the project directory

Create database in mysql phpmyadmin with name "timesheet"

Enter database connection configuration in .env file.

Example - 

`DB_CONNECTION=mysql`
`DB_HOST=localhost`
`DB_PORT=3306`
`DB_DATABASE=timesheet`
`DB_USERNAME=root`
`DB_PASSWORD=`
 
then run 

`$ php artisan migrate` command.

**Comment by vasanthkumaur** [comment]
The application is working perfectly. Thank you so much for your support.

**Comment by nitinsinghnaruka** [comment]
> The application is working perfectly. Thank you so much for your support.

My Pleasure.
